version: '3.8'
services:
  db:
    image: postgres:14-alpine
    ports:
      - '15432:5432'
    volumes:
      - pixelsdb:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    restart: always

  redis:
    image: redis:latest
    ports:
      - '${REDIS_PORT}:6379'
    command: >
      --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    volumes:
      - redis:/data

  api:
    build:
        context: .
        dockerfile: doge-pixels.Dockerfile
        target: development
    volumes:
      - .:/usr/src/app
      # anonymous volume so container deps are not overwritten by host
      - /usr/src/app/node_modules
    env_file:
      - .env
    # https://github.com/prisma/prisma/issues/1385
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:?No postgres user proivded}:${POSTGRES_PASSWORD:?No db password provided}@db:5432/${POSTGRES_DB:?No db provided}?schema=public
    command: yarn start:debug
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
      - redis


volumes:
    pixelsdb:
    redis:
      driver: local

