
name: '[prod:server]: build, deploy'

on:
  push:
    branches: master
    paths:
      - packages/server/src/**
      - packages/server/prisma/**

defaults:
  run:
    shell: bash

env:
  DOCKER_REGISTRY: calebcarithers

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - run: |
          export BUILD_ID="$GITHUB_SHA"
          source .github/scripts/build.sh
          buildApi

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: |
          export BUILD_ID="$GITHUB_SHA"
          source .github/scripts/build.sh
          pushImage

      - name: Ping webhook
        run: |
          curl "http://143.244.147.62:3009/paragraph-restrict-hip-ambiguous-hand-fascinate?SHA1=$GITHUB_SHA&env=production"

